version: '3.3'

volumes:
  pg_food:
  static:
  media:

services:

  db_food:
    image: postgres:13.10
    restart: always
    env_file: .env
    volumes:
      - pg_food:/var/lib/postgresql/data

  backend:
    image: astnikita/foodgram_backend
    restart: always
    env_file: .env
    depends_on:
      - db_food
    volumes:
      - static:/backend_static
      - media:/media

  frontend:
    image: astnikita/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  gateway:
    image: astnikita/foodgram_gateway
    env_file: .env
    volumes:
      - static:/staticfiles/
      - media:/media
    ports:
      - 8000:80
  
