version: '3.3'

volumes:
  pg_food:
  static:
  media:

services:

  db_food:
    image: postgres:13.10
    restart: always
    env_file: .env
    volumes:
      - pg_food:/var/lib/postgresql/data

  backend:
    build: ./backend/
    restart: always
    env_file: .env
    depends_on:
      - db_food
    volumes:
      - static:/backend_static
      - media:/media
      - ./backend/:/app

  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends_on:
      - backend

  gateway:
    build: ./gateway/
    restart: always
    volumes:
      - static:/staticfiles/
      - media:/media
    ports:
      - 8000:80
    depends_on:
      - frontend 
